import { ROUTE_PATHS } from './routes';
import { ChangeTypes } from './type';

export const enum ROLES {
    ARTIST,
    ADMIN,
    //VISITOR
}

//const VISITOR_PERMISSION: ROLES[] = [ROLES.VISITOR];
const ARTIST_PERMISSION: ROLES[] = [ROLES.ARTIST];
const ADMIN_PERMISSION: ROLES[] = [ROLES.ADMIN, ...ARTIST_PERMISSION];

export const PERMISSIONS: Partial<ChangeTypes<typeof ROUTE_PATHS, ROLES[]>> = {
    ADD: ADMIN_PERMISSION,
    EDIT: ARTIST_PERMISSION,
    EDIT_ARTIST_ACCOUNT: ADMIN_PERMISSION,
    EDIT_ARTIST_PROFILE: ARTIST_PERMISSION,
};
