export enum ROUTE_PATHS {
    HOME = '/',
    LOGIN = '/login',
    ARTISTS = '/artistAccounts',
    ADD = '/add/',
    ADD_NEW_ARTIST = 'addNewArtist',
    EDIT = '/edit/',
    EDIT_ARTIST_ACCOUNTS = 'artistAccounts',
    EDIT_ARTIST_PROFILE = 'artistProfile',
    EDIT_ANNOUNCEMENTS = 'announcements',
    EDIT_EXHIBITIONS = 'exhibitions',
    EDIT_EXHIBITION = 'exhibition',
    ARTIST_PROFILE = '/artistProfile',
    ABOUT = '/about',
    EXHIBITIONS = '/exhibitions',
    EXHIBITION = '/exhibition',
    VIRTUAL_EXHIBITION = '/virtualExhibition',
}