export enum ROUTE_PATHS {
    HOME = '/',
    LOGIN = '/login',
    REGISTER = '/register',
    ARTISTS = '/artistAccounts',
    EDIT_ARTIST_ACCOUNTS = '/edit/artistAccounts',
    EDIT_ARTIST_PROFILE = '/edit/artistProfile',
    EDIT_ANNOUNCEMENTS = '/edit/announcements',
    EDIT_EXHIBITIONS = '/edit/exhibitions',
    EDIT_EXHIBITION = '/edit/exhibition',
    ARTIST_PROFILE = '/artistProfile',
    ABOUT = '/about',
    CONTACT = '/contact',
    EXHIBITIONS = '/exhibitions',
    EXHIBITION = '/exhibition',
    VIRTUAL_EXHIBITION = '/virtualExhibition',
}